package main

import (
	"encoding/json"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// apiError carries an HTTP status so handlers can map failures consistently.
type apiError struct {
	Status int
	Msg    string
}

func (e *apiError) Error() string { return e.Msg }

type keySpec struct {
	secret   bool
	validate func(string) error
}

// mutableKeys is the server-enforced whitelist. Anything absent is blocked (403).
var mutableKeys = map[string]keySpec{
	"SCHEDULE":                 {validate: validateCron},
	"BACKUP_KEEP_MINS":         {validate: validateUint},
	"BACKUP_KEEP_DAYS":         {validate: validateUint},
	"BACKUP_KEEP_WEEKS":        {validate: validateUint},
	"BACKUP_KEEP_MONTHS":       {validate: validateUint},
	"POSTGRES_DB":              {validate: validateAny},
	"POSTGRES_DB_AUTODISCOVER": {validate: validateBoolWord},
	"POSTGRES_DB_EXCLUDE":      {validate: validateAny},
	"POSTGRES_EXTRA_OPTS":      {validate: validateAny},
	"POSTGRES_EXCLUDE_TABLES":  {validate: validateAny},
	"TELEGRAM_CHAT_ID":         {validate: validateAny},
	"TELEGRAM_THREAD_ID":       {validate: validateAny},
	"TELEGRAM_NOTIFY_ON":       {validate: validateNotifyOn},
	"TELEGRAM_API_URL":         {validate: validateURL},
	"BACKUP_MIN_DISK_SPACE":    {validate: validateUint},
	"BACKUP_MAX_AGE_HOURS":     {validate: validateUint},
	"WEBHOOK_EXTRA_ARGS":       {validate: validateAny},
	"TELEGRAM_BOT_TOKEN":       {secret: true, validate: validateNonEmpty},
	"TELEGRAM_API_ID":          {secret: true, validate: validateUint},
	"TELEGRAM_API_HASH":        {secret: true, validate: validateNonEmpty},
	"WEBHOOK_URL":              {secret: true, validate: validateURL},
}

const ScheduleKey = "SCHEDULE"

func backupDir() string {
	if d := os.Getenv("BACKUP_DIR"); d != "" {
		return d
	}
	return "/backups"
}

func overrideJSONPath() string { return filepath.Join(backupDir(), ".api-overrides.json") }
func overrideEnvPath() string  { return filepath.Join(backupDir(), ".api-overrides.env") }

// shellSingleQuote wraps s in single quotes, escaping embedded single quotes.
func shellSingleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

func loadOverrides() (map[string]string, error) {
	m := map[string]string{}
	raw, err := os.ReadFile(overrideJSONPath())
	if os.IsNotExist(err) {
		return m, nil
	}
	if err != nil {
		return nil, err
	}
	if err := json.Unmarshal(raw, &m); err != nil {
		return nil, err
	}
	return m, nil
}

// writeFileAtomic writes data to path via a temp file in the same dir + rename,
// so a partial write can never leave a half-written file in place.
func writeFileAtomic(path string, data []byte) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".tmp-*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName) // no-op after a successful rename
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Chmod(0o600); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpName, path)
}

func saveOverrides(m map[string]string) error {
	raw, err := json.Marshal(m)
	if err != nil {
		return err
	}
	if err := writeFileAtomic(overrideJSONPath(), raw); err != nil {
		return err
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	b.WriteString("# Generated by pgbackup-api. Do not edit by hand.\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "export %s=%s\n", k, shellSingleQuote(m[k]))
	}
	return writeFileAtomic(overrideEnvPath(), []byte(b.String()))
}

func validatePatch(patch map[string]string) error {
	for k, v := range patch {
		spec, ok := mutableKeys[k]
		if !ok {
			return &apiError{Status: 403, Msg: "config key not allowed: " + k}
		}
		if strings.ContainsAny(v, "\n\r\x00") {
			return &apiError{Status: 400, Msg: "value contains control characters: " + k}
		}
		if err := spec.validate(v); err != nil {
			return &apiError{Status: 400, Msg: fmt.Sprintf("invalid value for %s: %v", k, err)}
		}
	}
	return nil
}

func applyPatch(patch map[string]string) (scheduleChanged bool, err error) {
	if err = validatePatch(patch); err != nil {
		return false, err
	}
	cur, err := loadOverrides()
	if err != nil {
		return false, err
	}
	for k, v := range patch {
		if k == ScheduleKey && cur[k] != v {
			scheduleChanged = true
		}
		cur[k] = v
	}
	if err = saveOverrides(cur); err != nil {
		return false, err
	}
	return scheduleChanged, nil
}

func clearOverride(key string) (existed bool, err error) {
	if _, ok := mutableKeys[key]; !ok {
		return false, &apiError{Status: 403, Msg: "config key not allowed: " + key}
	}
	cur, err := loadOverrides()
	if err != nil {
		return false, err
	}
	if _, existed = cur[key]; !existed {
		return false, nil
	}
	delete(cur, key)
	if err = saveOverrides(cur); err != nil {
		return false, err
	}
	return true, nil
}

func effectiveConfig() (map[string]any, error) {
	ov, err := loadOverrides()
	if err != nil {
		return nil, err
	}
	out := map[string]any{}
	for k, spec := range mutableKeys {
		val, fromOverride := ov[k]
		source := "base"
		if fromOverride {
			source = "override"
		} else {
			val = os.Getenv(k)
		}
		if spec.secret {
			out[k] = map[string]any{"set": val != "", "source": source}
		} else {
			out[k] = map[string]any{"value": val, "source": source}
		}
	}
	return out, nil
}

func validateAny(string) error { return nil }
func validateNonEmpty(s string) error {
	if s == "" {
		return fmt.Errorf("must not be empty")
	}
	return nil
}
func validateUint(s string) error {
	if _, err := strconv.ParseUint(s, 10, 64); err != nil {
		return fmt.Errorf("must be a non-negative integer")
	}
	return nil
}
func validateBoolWord(s string) error {
	if s != "TRUE" && s != "FALSE" {
		return fmt.Errorf("must be TRUE or FALSE")
	}
	return nil
}
func validateNotifyOn(s string) error {
	switch s {
	case "all", "success", "failure":
		return nil
	}
	return fmt.Errorf("must be all, success, or failure")
}
func validateURL(s string) error {
	u, err := url.Parse(s)
	if err != nil || (u.Scheme != "http" && u.Scheme != "https") || u.Host == "" {
		return fmt.Errorf("must be an http(s) URL")
	}
	return nil
}
func validateCron(s string) error {
	if s == "" {
		return fmt.Errorf("must not be empty")
	}
	if strings.HasPrefix(s, "@") {
		switch s {
		case "@yearly", "@annually", "@monthly", "@weekly", "@daily", "@hourly":
			return nil
		}
		if after, ok := strings.CutPrefix(s, "@every "); ok {
			if strings.TrimSpace(after) == "" {
				return fmt.Errorf("@every requires a duration, e.g. @every 1h30m")
			}
			return nil
		}
		return fmt.Errorf("unknown schedule shortcut")
	}
	// Per-field cron syntax is validated by go-cron at apply time; this only checks shape.
	if n := len(strings.Fields(s)); n != 5 && n != 6 {
		return fmt.Errorf("cron expression must have 5 or 6 fields")
	}
	return nil
}
