#!/usr/bin/env bash
# Builds a PostgreSQL server shaped like the Pharmakon platform, so the backup
# pipeline can be tested against it: the svc_* logins, the control database, two
# healthy pharmacy databases (branch schemas brNN, public with Riayati tables under
# row-level security, reporting views, a schema_migrations ledger), a restore
# set-aside copy (br01_before_<14 digits>), a pharmacy whose provisioning failed
# (svc_backup has no CONNECT) and an analytics database outside the name filter.
# Mirrors infra/stacks/platform/config/init.sh, db/pharmacy/*.sql and
# src/control-api/apps/tenancy/provisioning.py in the Pharmakon repository.
# Idempotent: drops and rebuilds everything it owns. Works on PostgreSQL 16+.
# Env: POSTGRES_HOST, POSTGRES_PORT, SU_USER/SU_PASSWORD (or POSTGRES_USER/PASSWORD) — a superuser.
set -Eeo pipefail

SU_USER="${SU_USER:-${POSTGRES_USER}}"
SU_PASSWORD="${SU_PASSWORD:-${POSTGRES_PASSWORD}}"
SVC_PASSWORD="svc_pw"   # test-only: every svc_* login shares it

su_sql() {
  PGPASSWORD="${SU_PASSWORD}" psql -X -q -v ON_ERROR_STOP=1 \
    -h "${POSTGRES_HOST}" -p "${POSTGRES_PORT:-5432}" -U "${SU_USER}" "$@"
}

# Everything in control and the pharmacy databases is owned by svc_control_api, as on the platform.
api_sql() {
  PGPASSWORD="${SVC_PASSWORD}" psql -X -q -v ON_ERROR_STOP=1 \
    -h "${POSTGRES_HOST}" -p "${POSTGRES_PORT:-5432}" -U svc_control_api "$@"
}

# --- Server-level: logins and databases (init.sh) ---------------------------
su_sql -d postgres -v pw="${SVC_PASSWORD}" <<'SQL'
DROP DATABASE IF EXISTS control WITH (FORCE);
DROP DATABASE IF EXISTS pharmacy_alpha WITH (FORCE);
DROP DATABASE IF EXISTS pharmacy_beta WITH (FORCE);
DROP DATABASE IF EXISTS pharmacy_broken WITH (FORCE);
DROP DATABASE IF EXISTS analytics WITH (FORCE);
DROP ROLE IF EXISTS ph_alpha_ho, ph_alpha_br01, ph_alpha_br02,
  ph_beta_ho, ph_beta_br01, ph_beta_br02, ph_beta_br100, ph_broken_ho;
DO $$
DECLARE r text;
BEGIN
  FOREACH r IN ARRAY ARRAY['svc_control_api', 'svc_backup_api', 'svc_fglobal_api', 'svc_backup', 'svc_warehouse', 'svc_monitor'] LOOP
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = r) THEN
      EXECUTE format('CREATE ROLE %I LOGIN', r);
    END IF;
  END LOOP;
END $$;
ALTER ROLE svc_control_api WITH LOGIN CREATEDB CREATEROLE NOSUPERUSER NOBYPASSRLS PASSWORD :'pw';
ALTER ROLE svc_backup_api WITH LOGIN NOSUPERUSER NOBYPASSRLS PASSWORD :'pw';
ALTER ROLE svc_fglobal_api WITH LOGIN NOSUPERUSER NOBYPASSRLS PASSWORD :'pw';
ALTER ROLE svc_backup WITH LOGIN NOSUPERUSER NOBYPASSRLS CONNECTION LIMIT 5 PASSWORD :'pw';
ALTER ROLE svc_warehouse WITH LOGIN NOSUPERUSER NOBYPASSRLS PASSWORD :'pw';
ALTER ROLE svc_monitor WITH LOGIN NOSUPERUSER NOBYPASSRLS CONNECTION LIMIT 5 PASSWORD :'pw';
GRANT pg_signal_backend TO svc_control_api WITH INHERIT TRUE, SET FALSE;
GRANT pg_read_all_data TO svc_backup WITH INHERIT TRUE, SET FALSE;
GRANT pg_read_all_data TO svc_warehouse WITH INHERIT TRUE, SET FALSE;
GRANT pg_monitor TO svc_monitor WITH INHERIT TRUE, SET FALSE;
GRANT CONNECT ON DATABASE postgres TO svc_monitor, svc_backup;
REVOKE CONNECT, TEMPORARY ON DATABASE postgres FROM PUBLIC;
REVOKE CONNECT ON DATABASE template1 FROM PUBLIC;
CREATE DATABASE control OWNER svc_control_api;
GRANT CONNECT ON DATABASE control TO svc_control_api, svc_backup_api, svc_fglobal_api, svc_backup, svc_warehouse;
REVOKE CONNECT, TEMPORARY ON DATABASE control FROM PUBLIC;
CREATE DATABASE analytics OWNER svc_warehouse;
REVOKE CONNECT, TEMPORARY ON DATABASE analytics FROM PUBLIC;
SQL

# --- control: the console's directory (Django tenancy app, trimmed) ----------
api_sql -d control <<'SQL'
CREATE TABLE tenancy_pharmacy (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code text NOT NULL UNIQUE,
  name text NOT NULL, status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE tenancy_branch (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pharmacy_id bigint NOT NULL REFERENCES tenancy_pharmacy (id), number smallint NOT NULL, name text NOT NULL,
  UNIQUE (pharmacy_id, number));
CREATE TABLE tenancy_provisioningjob (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pharmacy_id bigint REFERENCES tenancy_pharmacy (id), kind text NOT NULL, status text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now());
INSERT INTO tenancy_pharmacy (code, name, status) VALUES ('alpha', 'Alpha', 'active'), ('beta', 'Beta', 'active'),
  ('broken', 'Broken', 'failed');
INSERT INTO tenancy_branch (pharmacy_id, number, name) VALUES (1, 1, 'Alpha 1'), (1, 2, 'Alpha 2'), (2, 1, 'Beta 1'),
  (2, 2, 'Beta 2'), (2, 100, 'Beta 100');
INSERT INTO tenancy_provisioningjob (pharmacy_id, kind, status) VALUES (1, 'create_pharmacy', 'succeeded'),
  (2, 'create_pharmacy', 'succeeded'), (3, 'create_pharmacy', 'failed');
GRANT SELECT ON tenancy_pharmacy, tenancy_branch TO svc_backup_api, svc_fglobal_api;
SQL

# One branch schema: tables from db/pharmacy/0001_init.branch.sql, the security_invoker
# view from 0002_reporting.branch.sql, <rows> rows of data, and (unless <ledger> is FALSE)
# its schema_migrations rows. The set-aside copy gets none: the ledger is keyed by target name.
branch_sql() {
  local schema="$1" number="$2" rows="$3" ledger="${4:-TRUE}"
  cat <<SQL
CREATE SCHEMA ${schema};
SET LOCAL search_path TO ${schema};
CREATE TABLE otdel (id_global bigint PRIMARY KEY, name text, adress text, state bigint, dt bigint, plus bigint,
  day bigint, data timestamp, datachange_global timestamp NOT NULL DEFAULT now());
CREATE TABLE failures (id_global bigint PRIMARY KEY, good bigint, sgood bigint, name text, kol bigint, otdel bigint,
  dataenter timestamp, datachange_global timestamp NOT NULL DEFAULT now());
ALTER TABLE failures ADD CONSTRAINT failures_otdel_fkey FOREIGN KEY (otdel) REFERENCES otdel (id_global)
  DEFERRABLE INITIALLY IMMEDIATE;
CREATE INDEX failures_otdel_idx ON failures (otdel);
CREATE TABLE sync_rejects (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, table_name text NOT NULL,
  id_global bigint, code text NOT NULL, detail text NOT NULL, payload jsonb NOT NULL,
  received_at timestamp NOT NULL DEFAULT now());
CREATE VIEW branches WITH (security_invoker = true) AS
SELECT COALESCE(d.pos_number, d.number)::integer AS id_global, d.name::varchar(50) AS name,
       o.adress::varchar(80) AS adress, o.state::integer AS state, d.number AS branch_no
FROM public.branch_directory d LEFT JOIN otdel o ON o.id_global = d.pos_number
WHERE d.number = ${number};
INSERT INTO otdel (id_global, name, adress, state) SELECT g, 'Otdel ' || g, 'Street ' || g, 1 FROM generate_series(1, ${rows}) g;
INSERT INTO failures (id_global, good, name, kol, otdel, dataenter)
  SELECT g, g * 10, 'Item ' || g, g % 7, 1 + (g % GREATEST(${rows}, 1)), now() FROM generate_series(1, ${rows} * 2) g
  WHERE ${rows} > 0;
INSERT INTO sync_rejects (table_name, id_global, code, detail, payload)
  SELECT 'otdel', 1, 'duplicate', 'fixture row', '{"k": 1}'::jsonb WHERE ${rows} > 0;
SET LOCAL search_path TO public;
SQL
  if [ "${ledger}" = "TRUE" ]; then
    echo "INSERT INTO public.schema_migrations (version, target) VALUES ('0001_init', '${schema}'), ('0002_reporting', '${schema}'), ('0013_warehouse', '${schema}');"
  fi
}

# A pharmacy's roles, created by svc_control_api (CREATEROLE gives it ADMIN), as provisioning.py does.
pharmacy_roles_sql() {
  local code="$1"; shift
  local n
  echo "CREATE ROLE ph_${code}_ho NOLOGIN;"
  echo "GRANT ph_${code}_ho TO svc_fglobal_api WITH INHERIT FALSE, SET TRUE;"
  for n in "$@"; do
    echo "CREATE ROLE ph_${code}_br${n} NOLOGIN;"
    echo "GRANT ph_${code}_br${n} TO svc_backup_api WITH INHERIT FALSE, SET TRUE;"
    echo "GRANT ph_${code}_br${n} TO svc_fglobal_api WITH INHERIT FALSE, SET TRUE;"
  done
}

# ensure_database: the database, PUBLIC locked out, only svc_backup_api may connect (provisioning.py).
create_pharmacy_database() {
  local db="$1"
  api_sql -d control -c "CREATE DATABASE ${db}"
  api_sql -d control <<SQL
REVOKE CONNECT ON DATABASE ${db} FROM PUBLIC;
REVOKE TEMPORARY ON DATABASE ${db} FROM PUBLIC;
GRANT CONNECT ON DATABASE ${db} TO svc_backup_api;
SQL
}

# The whole migrated pharmacy in one transaction, ending with grant_access — the only place
# svc_backup gets CONNECT. <setaside> = TRUE builds br01 first with stale rows and renames it
# to br01_before_20260930141503, as backup-runner's set-aside does before a branch restore.
build_pharmacy() {
  local code="$1" setaside="$2"; shift 2
  local db="pharmacy_${code}" n schema rls
  {
    echo "BEGIN;"
    cat <<'SQL'
CREATE TABLE public.schema_migrations (version text NOT NULL, target text NOT NULL,
  applied_at timestamp NOT NULL DEFAULT now(), PRIMARY KEY (version, target));
CREATE TABLE public.accounts (user_name text PRIMARY KEY, branch_no smallint NOT NULL, password_hash text NOT NULL);
CREATE TABLE public.branch_directory (number smallint PRIMARY KEY, pos_number bigint, name text NOT NULL);
CREATE TABLE public.kpi_threshold_rules (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, metric text NOT NULL,
  threshold numeric NOT NULL);
CREATE SCHEMA reporting;
CREATE TABLE reporting.dashboard_users (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, email text NOT NULL UNIQUE);
CREATE TABLE reporting.user_branches (user_id bigint NOT NULL REFERENCES reporting.dashboard_users (id),
  branch_no smallint NOT NULL REFERENCES public.branch_directory (number), PRIMARY KEY (user_id, branch_no));
CREATE TABLE public.riayati_transaction (id text PRIMARY KEY, branch_no smallint NOT NULL, control_id text NOT NULL UNIQUE,
  message_type text NOT NULL, status text NOT NULL, created_at timestamp NOT NULL DEFAULT now(), UNIQUE (id, branch_no));
CREATE TABLE public.riayati_message (id text PRIMARY KEY, transaction_id text NOT NULL, branch_no smallint NOT NULL,
  direction text NOT NULL, body text NOT NULL,
  FOREIGN KEY (transaction_id, branch_no) REFERENCES public.riayati_transaction (id, branch_no));
SQL
    # Row-level security exactly as db/pharmacy/0012_riayati.public.sql and 0013_warehouse.public.sql: ENABLE, never FORCE.
    for rls in riayati_transaction riayati_message; do
      cat <<SQL
ALTER TABLE public.${rls} ENABLE ROW LEVEL SECURITY;
CREATE POLICY branch_rows ON public.${rls}
  USING (branch_no = current_setting('pharmakan.branch_no')::smallint)
  WITH CHECK (branch_no = current_setting('pharmakan.branch_no')::smallint);
CREATE POLICY backup_reads_all ON public.${rls} FOR SELECT TO svc_backup USING (true);
CREATE POLICY warehouse_reads_none ON public.${rls} AS RESTRICTIVE FOR ALL TO svc_warehouse USING (false);
SQL
    done
    echo "INSERT INTO public.schema_migrations (version, target) VALUES ('0001_init', 'public'), ('0002_reporting', 'public'), ('0012_riayati', 'public'), ('0013_warehouse', 'public');"
    for n in "$@"; do
      echo "INSERT INTO public.branch_directory (number, pos_number, name) VALUES (${n#0}, NULL, 'Branch ${n}');"
      echo "INSERT INTO public.accounts (user_name, branch_no, password_hash) VALUES ('pos${n}', ${n#0}, 'x');"
      echo "INSERT INTO public.riayati_transaction (id, branch_no, control_id, message_type, status) SELECT 'tx-${n}-' || g, ${n#0}, 'ctl-${n}-' || g, 'RDS^O13', 'acked' FROM generate_series(1, 20) g;"
      echo "INSERT INTO public.riayati_message (id, transaction_id, branch_no, direction, body) SELECT 'msg-${n}-' || g, 'tx-${n}-' || g, ${n#0}, 'out', repeat('MSH|', 20) FROM generate_series(1, 20) g;"
    done
    echo "INSERT INTO public.kpi_threshold_rules (metric, threshold) VALUES ('stock_days', 14), ('expiry_days', 90);"
    echo "INSERT INTO reporting.dashboard_users (email) VALUES ('owner@${code}.test');"
    branch_sql branch_template 0 0
    if [ "${setaside}" = "TRUE" ]; then
      branch_sql br01 1 7 FALSE
      echo "ALTER SCHEMA br01 RENAME TO br01_before_20260930141503;"
    fi
    for n in "$@"; do
      branch_sql "br${n}" "${n#0}" 50
    done
    # rebuild_reporting: one UNION ALL view per branch_template view, over ^br[0-9]{2,3}$ only.
    cat <<'SQL'
DO $$
DECLARE v text; src text;
BEGIN
  FOR v IN SELECT viewname FROM pg_views WHERE schemaname = 'branch_template' ORDER BY 1 LOOP
    SELECT string_agg(format('SELECT * FROM %I.%I', nspname, v), ' UNION ALL ' ORDER BY nspname) INTO src
      FROM pg_namespace WHERE nspname ~ '^br[0-9]{2,3}$';
    EXECUTE format('DROP VIEW IF EXISTS reporting.%I CASCADE', v);
    EXECUTE format('CREATE VIEW reporting.%I WITH (security_invoker = true) AS %s', v, src);
  END LOOP;
END $$;
SQL
    # grant_access (provisioning.py): the only place svc_backup gets CONNECT.
    cat <<SQL
GRANT CONNECT ON DATABASE ${db} TO svc_backup_api, svc_fglobal_api, svc_backup, svc_warehouse;
GRANT USAGE ON SCHEMA public TO svc_backup_api, svc_fglobal_api, ph_${code}_ho;
GRANT SELECT ON public.accounts TO svc_backup_api;
GRANT SELECT ON public.branch_directory TO svc_fglobal_api, ph_${code}_ho;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.kpi_threshold_rules TO ph_${code}_ho;
GRANT USAGE ON SCHEMA branch_template TO svc_backup_api, ph_${code}_ho;
GRANT SELECT ON ALL TABLES IN SCHEMA branch_template TO ph_${code}_ho;
GRANT USAGE ON SCHEMA reporting TO svc_fglobal_api, ph_${code}_ho;
GRANT SELECT, UPDATE ON reporting.dashboard_users TO svc_fglobal_api;
GRANT SELECT ON reporting.user_branches TO svc_fglobal_api;
GRANT SELECT ON reporting.branches TO ph_${code}_ho;
SQL
    for n in "$@"; do
      schema="br${n}"
      cat <<SQL
GRANT USAGE ON SCHEMA ${schema} TO ph_${code}_ho;
GRANT SELECT ON ALL TABLES IN SCHEMA ${schema} TO ph_${code}_ho;
GRANT USAGE ON SCHEMA ${schema} TO ph_${code}_br${n};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ${schema} TO ph_${code}_br${n};
GRANT USAGE ON ALL SEQUENCES IN SCHEMA ${schema} TO ph_${code}_br${n};
GRANT SELECT ON public.branch_directory, public.kpi_threshold_rules TO ph_${code}_br${n};
GRANT SELECT, INSERT, UPDATE, DELETE ON public.riayati_transaction, public.riayati_message TO ph_${code}_br${n};
SQL
    done
    echo "COMMIT;"
  } | api_sql -d "${db}"
}

api_sql -d control -c "$(pharmacy_roles_sql alpha 01 02)"
api_sql -d control -c "$(pharmacy_roles_sql beta 01 02 100)"
api_sql -d control -c "$(pharmacy_roles_sql broken)"

create_pharmacy_database pharmacy_alpha
build_pharmacy alpha TRUE 01 02

create_pharmacy_database pharmacy_beta
build_pharmacy beta FALSE 01 02 100

# A pharmacy whose provisioning transaction rolled back: the database and its head-office
# role exist, nothing else — svc_backup has no CONNECT.
create_pharmacy_database pharmacy_broken

echo "✅ Pharmakon fixture ready: control, pharmacy_alpha, pharmacy_beta, pharmacy_broken, analytics."
